/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
export const SET_SYSTEM_PREFERENCE = 'SET_SYSTEM_PREFERENCE';

// Preferences
export const SET_PREFERENCE = 'SET_PREFERENCE';
export const SET_PREFERENCES = 'SET_PREFERENCES';

// Workspaces
export const SET_WORKSPACE = 'SET_WORKSPACE';
export const SET_WORKSPACES = 'SET_WORKSPACES';

// Workspace Metas
export const SET_WORKSPACE_META = 'SET_WORKSPACE_META';
export const SET_WORKSPACE_METAS = 'SET_WORKSPACE_METAS';

// Edit Workspace
export const OPEN_EDIT_WORKSPACE = 'OPEN_EDIT_WORKSPACE';
export const CLOSE_EDIT_WORKSPACE = 'CLOSE_EDIT_WORKSPACE';
export const UPDATE_EDIT_WORKSPACE_FORM = 'UPDATE_EDIT_WORKSPACE_FORM';
export const UPDATE_EDIT_WORKSPACE_DOWNLOADING_ICON = 'UPDATE_EDIT_WORKSPACE_DOWNLOADING_ICON';

// General
export const UPDATE_CAN_GO_BACK = 'UPDATE_CAN_GO_BACK';
export const UPDATE_CAN_GO_FORWARD = 'UPDATE_CAN_GO_FORWARD';
export const UPDATE_SHOULD_USE_DARK_COLORS = 'UPDATE_SHOULD_USE_DARK_COLORS';
export const UPDATE_IS_FULL_SCREEN = 'UPDATE_IS_FULL_SCREEN';
export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_IS_MAXIMIZED = 'UPDATE_IS_MAXIMIZED';
export const UPDATE_LOCKED = 'UPDATE_LOCKED';

// Find In Page
export const CLOSE_FIND_IN_PAGE = 'CLOSE_FIND_IN_PAGE';
export const OPEN_FIND_IN_PAGE = 'OPEN_FIND_IN_PAGE';
export const UPDATE_FIND_IN_PAGE_TEXT = 'UPDATE_FIND_IN_PAGE_TEXT';
export const UPDATE_FIND_IN_PAGE_MATCHES = 'UPDATE_FIND_IN_PAGE_MATCHES';

// Code Injection
export const UPDATE_CODE_INJECTION_FORM = 'UPDATE_CODE_INJECTION_FORM';
export const OPEN_CODE_INJECTION_FORM = 'OPEN_CODE_INJECTION_FORM';
export const CLOSE_CODE_INJECTION_FORM = 'CLOSE_CODE_INJECTION_FORM';

// Custom User Agent
export const UPDATE_CUSTOM_USER_AGENT_FORM = 'UPDATE_CUSTOM_USER_AGENT_FORM';
export const OPEN_CUSTOM_USER_AGENT_FORM = 'OPEN_CUSTOM_USER_AGENT_FORM';
export const CLOSE_CUSTOM_USER_AGENT_FORM = 'CLOSE_CUSTOM_USER_AGENT_FORM';

// Go To URL
export const UPDATE_ADDRESS_BAR_INFO = 'UPDATE_ADDRESS_BAR_INFO';

// Go To URL
export const UPDATE_GO_TO_URL_FORM = 'UPDATE_GO_TO_URL_FORM';

// Auth
export const UPDATE_AUTH_FORM = 'UPDATE_AUTH_FORM';

// Notifications
export const UPDATE_PAUSE_NOTIFICATIONS_INFO = 'UPDATE_PAUSE_NOTIFICATIONS_INFO';
export const UPDATE_SHOW_DATE_TIME_PICKER = 'UPDATE_SHOW_DATE_TIME_PICKER';

// Proxy
export const DIALOG_PROXY_FORM_UPDATE = 'DIALOG_PROXY_FORM_UPDATE';
export const DIALOG_PROXY_OPEN = 'DIALOG_PROXY_OPEN';
export const DIALOG_PROXY_CLOSE = 'DIALOG_PROXY_CLOSE';

// Spell Check Languages
export const DIALOG_SPELLCHECK_LANGUAGES_UPDATE_FORM = 'DIALOG_SPELLCHECK_LANGUAGES_UPDATE_FORM';
export const DIALOG_SPELLCHECK_LANGUAGES_OPEN = 'DIALOG_SPELLCHECK_LANGUAGES_OPEN';
export const DIALOG_SPELLCHECK_LANGUAGES_CLOSE = 'DIALOG_SPELLCHECK_LANGUAGES_CLOSE';

// Add Workspace
export const ADD_WORKSPACE_UPDATE_DOWNLOADING_ICON = 'ADD_WORKSPACE_UPDATE_DOWNLOADING_ICON';
export const ADD_WORKSPACE_UPDATE_FORM = 'ADD_WORKSPACE_UPDATE_FORM';
export const ADD_WORKSPACE_UPDATE_MODE = 'ADD_WORKSPACE_UPDATE_MODE';
export const ADD_WORKSPACE_RESET_FORM = 'ADD_WORKSPACE_RESET_FORM';

// Internal URLS
export const UPDATE_DIALOG_INTERNAL_URLS = 'UPDATE_DIALOG_INTERNAL_URLS';
export const OPEN_DIALOG_INTERNAL_URLS = 'OPEN_DIALOG_INTERNAL_URLS';
export const CLOSE_DIALOG_INTERNAL_URLS = 'CLOSE_DIALOG_INTERNAL_URLS';

// External URLS
export const UPDATE_DIALOG_EXTERNAL_URLS = 'UPDATE_DIALOG_EXTERNAL_URLS';
export const OPEN_DIALOG_EXTERNAL_URLS = 'OPEN_DIALOG_EXTERNAL_URLS';
export const CLOSE_DIALOG_EXTERNAL_URLS = 'CLOSE_DIALOG_EXTERNAL_URLS';

// Customize Fonts
export const UPDATE_DIALOG_CUSTOMIZE_FONTS = 'UPDATE_DIALOG_CUSTOMIZE_FONTS';
export const OPEN_DIALOG_CUSTOMIZE_FONTS = 'OPEN_DIALOG_CUSTOMIZE_FONTS';
export const CLOSE_DIALOG_CUSTOMIZE_FONTS = 'CLOSE_DIALOG_CUSTOMIZE_FONTS';

// Workspace Preferences
export const UPDATE_WORKSPACE_PREFERENCES_FORM = 'UPDATE_WORKSPACE_PREFERENCES_FORM';
export const UPDATE_WORKSPACE_PREFERENCES_DOWNLOADING_ICON = 'UPDATE_WORKSPACE_PREFERENCES_DOWNLOADING_ICON';

// Dialog App Lock
export const UPDATE_DIALOG_APP_LOCK = 'UPDATE_DIALOG_APP_LOCK';
export const OPEN_DIALOG_APP_LOCK = 'OPEN_DIALOG_APP_LOCK';
export const CLOSE_DIALOG_APP_LOCK = 'CLOSE_DIALOG_APP_LOCK';

// App Lock
export const UPDATE_APP_LOCK_FORM = 'UPDATE_APP_LOCK_FORM';

// Refresh Interval
export const UPDATE_REFRESH_INTERVAL_FORM = 'UPDATE__REFRESH_INTERVAL_FORM';
export const OPEN_REFRESH_INTERVAL_FORM = 'OPEN_REFRESH_INTERVAL_FORM';
export const CLOSE_REFRESH_INTERVAL_FORM = 'CLOSE_REFRESH_INTERVA_FORM';

// Dialog License Registration
export const DIALOG_LICENSE_REGISTRATION_FORM_UPDATE = 'DIALOG_LICENSE_REGISTRATION_FORM_UPDATE';

// Updater
export const UPDATE_UPDATER = 'UPDATE_UPDATER';
