/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
const {
  BrowserWindow,
  Menu,
  Tray,
  app,
  ipcMain,
  nativeImage,
} = require('electron');
const windowStateKeeper = require('electron-window-state');
const { menubar } = require('menubar');
const path = require('path');
const isDev = require('electron-is-dev');

const { REACT_PATH } = require('../constants/paths');
const { setPreference, getPreference } = require('../libs/preferences');
const isKdeAsync = require('../libs/is-kde-async');
const appJson = require('../constants/app-json');

let win;
let mb = {};
let tray;
let minimizedView;

const get = () => {
  if (global.attachToMenubar) return mb.window;
  return win;
};

const createAsync = () => new Promise((resolve) => {
  const handleTrayRightClick = () => {
    const muteApp = getPreference('muteApp');
    const lockMenuItems = Boolean(global.appLock) && !global.locked ? [
      {
        type: 'separator',
      },
      {
        label: 'Lock',
        click: () => ipcMain.emit('request-lock-app'),
      },
    ] : [];

    const contextMenu = Menu.buildFromTemplate([
      {
        label: `Open ${appJson.name}`,
        click: () => {
          if (global.attachToMenubar) {
            mb.showWindow();
            return;
          }

          if (win == null) {
            createAsync();
          } else {
            win.show();
          }
        },
      },
      {
        type: 'separator',
      },
      {
        label: `About ${appJson.name}`,
        click: () => ipcMain.emit('request-show-about-window'),
      },
      { type: 'separator' },
      ...lockMenuItems,
      {
        label: 'Check for Updates...',
        click: () => ipcMain.emit('request-check-for-updates'),
      },
      {
        type: 'separator',
      },
      {
        label: 'Notifications...',
        click: () => ipcMain.emit('request-show-notifications-window'),
        enabled: !global.locked,
      },
      { type: 'separator' },
      {
        label: muteApp ? 'Unmute' : 'Mute',
        click: () => setPreference('muteApp', !muteApp),
        enabled: !global.locked,
      },
      { type: 'separator' },
      {
        label: 'Preferences...',
        click: () => ipcMain.emit('request-show-preferences-window'),
      },
      { type: 'separator' },
      {
        label: 'Quit',
        click: () => {
          if (global.attachToMenubar) {
            mb.app.quit();
            return;
          }
          app.quit();
        },
      },
    ]);

    (global.attachToMenubar ? mb.tray : tray).popUpContextMenu(contextMenu);
  };

  if (global.attachToMenubar) {
    const menubarWindowState = windowStateKeeper({
      file: 'window-state-menubar.json',
      defaultWidth: 400,
      defaultHeight: 400,
    });

    // setImage after Tray instance is created to avoid
    // "Segmentation fault (core dumped)" bug on Linux
    // https://github.com/electron/electron/issues/22137#issuecomment-586105622
    // https://github.com/atomery/translatium/issues/164
    const menubarTray = new Tray(nativeImage.createEmpty());
    // icon template on macOS is only available for Singlebox, not apps generated by WebCatalog
    // icon template is not supported on Windows & Linux
    const iconPath = process.env.NODE_ENV === 'production'
      ? path.resolve(__dirname, 'menubar-icon.png')
      : path.resolve(__dirname, '..', '..', 'public', 'menubar-icon.png');
    menubarTray.setImage(iconPath);

    mb = menubar({
      index: REACT_PATH,
      tray: menubarTray,
      preloadWindow: true,
      tooltip: appJson.name,
      browserWindow: {
        alwaysOnTop: getPreference('alwaysOnTop'),
        x: menubarWindowState.x,
        y: menubarWindowState.y,
        width: menubarWindowState.width,
        height: menubarWindowState.height,
        minHeight: 100,
        minWidth: 400,
        webPreferences: {
          enableRemoteModule: true,
          contextIsolation: false,
          nodeIntegration: true,
          webSecurity: !isDev,
          preload: path.join(__dirname, 'menubar-preload.js'),
        },
      },
    });

    mb.on('after-create-window', () => {
      menubarWindowState.manage(mb.window);

      mb.window.on('focus', () => {
        const view = mb.window.getBrowserView();
        if (view && view.webContents) {
          view.webContents.focus();
        }
      });
    });

    mb.on('ready', () => {
      mb.tray.on('right-click', handleTrayRightClick);

      resolve();
    });
    return;
  }

  // check system-preferences.js
  // wasOpenedAsHidden is only available on macOS
  const { wasOpenedAsHidden } = app.getLoginItemSettings();

  const mainWindowState = windowStateKeeper({
    defaultWidth: 800,
    defaultHeight: 768,
  });

  const winOpts = {
    backgroundColor: '#FFF',
    x: mainWindowState.x,
    y: mainWindowState.y,
    width: mainWindowState.width,
    height: mainWindowState.height,
    minHeight: 100,
    minWidth: 400,
    title: global.appJson.name,
    // show traffic light buttons on macOS if global.windowButtons = true
    titleBarStyle: global.windowButtons ? 'hidden' : 'default',
    frame: (process.platform === 'darwin' && global.windowButtons) || global.useSystemTitleBar,
    show: false,
    webPreferences: {
      enableRemoteModule: true,
      contextIsolation: false,
      nodeIntegration: true,
      webSecurity: !isDev,
      preload: path.join(__dirname, 'main-preload.js'),
    },
  };
  // winOpts.icon cannot be set to undefined
  // as it'd crash Electron on macOS
  // https://github.com/electron/electron/issues/27303#issuecomment-759501184
  if (process.platform === 'linux') {
    winOpts.icon = process.env.NODE_ENV === 'production'
      ? path.resolve(__dirname, 'dock-icon.png')
      : path.resolve(__dirname, '..', '..', 'public', 'dock-icon.png');
  }
  win = new BrowserWindow(winOpts);

  mainWindowState.manage(win);

  // Enable swipe to navigate
  const swipeToNavigate = getPreference('swipeToNavigate');
  if (swipeToNavigate) {
    win.on('swipe', (e, direction) => {
      const view = win.getBrowserView();
      if (view) {
        if (direction === 'left') {
          view.webContents.goBack();
        } else if (direction === 'right') {
          view.webContents.goForward();
        }
      }
    });
  }

  // Hide window instead closing on macos
  win.on('close', (e) => {
    if ((process.platform === 'darwin' || global.runInBackground === true) && win && !win.forceClose) {
      e.preventDefault();
      // on Mac, app won't quit, so lock the app when window is closed but app stays in dock
      ipcMain.emit('request-lock-app');
      // https://github.com/electron/electron/issues/6033#issuecomment-242023295
      if (win.isFullScreen()) {
        win.once('leave-full-screen', () => {
          win.hide();
        });
        win.setFullScreen(false);
      } else {
        win.hide();
      }
    }
  });

  win.on('maximize', () => {
    win.webContents.send('set-is-maximized', true);
  });
  win.on('unmaximize', () => {
    win.webContents.send('set-is-maximized', false);
  });

  // If BrowserWindows has BrowserView attached
  // KDE Plasma desktop environment will refuse to minimize the app window
  // so we detach the BrowserView when minimizing and restore it later
  // https://github.com/webcatalog/webcatalog-app/issues/1201
  // only apply this bug fix in KDE Plasma environment
  // as it makes the app feels sluggish (it takes time to restore BrowserView)
  // also for unknown reason, win.on('restore') is not
  //  triggered on Windows (production-only, somehow it's working in dev)
  isKdeAsync()
    .then((isKde) => {
      if (!isKde) return;
      win.on('minimize', () => {
        minimizedView = win.getBrowserView();
        win.setBrowserView(null);
      });
      win.on('restore', () => {
        if (minimizedView != null) {
          win.setBrowserView(minimizedView);
          minimizedView = null;
        }
      });
    });

  win.on('closed', () => {
    win = null;
    minimizedView = null;
  });

  win.on('focus', () => {
    const view = win.getBrowserView();
    if (view && view.webContents) {
      view.webContents.focus();
    }
  });

  win.once('ready-to-show', () => {
    if (!wasOpenedAsHidden) {
      win.show();
    }

    // calling this to redundantly setBounds BrowserView
    // after the UI is fully loaded
    // if not, BrowserView mouseover event won't work correctly
    // https://github.com/webcatalog/webcatalog-app/issues/812
    ipcMain.emit('request-realign-active-workspace');
  });

  win.on('enter-full-screen', () => {
    win.webContents.send('is-fullscreen-updated', true);
    // it takes some time for the fullscreen state to populate
    setTimeout(() => {
      ipcMain.emit('request-realign-active-workspace');
    }, 500);
  });
  win.on('leave-full-screen', () => {
    win.webContents.send('is-fullscreen-updated', false);
    // it takes some time for the fullscreen state to populate
    setTimeout(() => {
      ipcMain.emit('request-realign-active-workspace');
    }, 500);
  });

  // ensure redux is loaded first
  // if not, redux might not be able catch changes sent from ipcMain
  win.webContents.once('did-stop-loading', () => {
    resolve();
  });

  win.loadURL(REACT_PATH);

  const shouldShowTray = global.trayIcon || (process.platform !== 'darwin' && global.runInBackground);
  if (shouldShowTray && tray == null) {
    tray = new Tray(nativeImage.createEmpty());
    // icon template on macOS is only available for Singlebox, not apps generated by WebCatalog
    // icon template is not supported on Windows & Linux
    const iconFileName = isMas() ? 'menubarTemplate.png' : 'menubar-icon.png';
    const iconPath = process.env.NODE_ENV === 'production'
      ? path.resolve(__dirname, iconFileName)
      : path.resolve(__dirname, '..', '..', 'public', iconFileName);
    tray.setImage(iconPath);
    tray.on('click', () => {
      if (win == null) {
        createAsync();
      } else {
        win.show();
      }
    });
    tray.setToolTip(app.name);
    tray.on('right-click', handleTrayRightClick);
  }
});

const show = () => {
  if (global.attachToMenubar) {
    if (mb == null) {
      createAsync();
    } else {
      mb.on('ready', () => {
        mb.showWindow();
      });
    }
  } else if (win == null) {
    createAsync();
  } else {
    win.show();
  }
};

const send = (...args) => {
  if (get() !== null) {
    get().webContents.send(...args);
  }
};

module.exports = {
  createAsync,
  get,
  send,
  show,
};
