name: Release API

on:
  release:
    types: [published, edited, deleted]
  pull_request:
    branches:
      - master
      - next
    paths:
      - 'scripts/update-versions-static-api.mjs'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: false
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn cache
        uses: actions/cache@v2
        id: cache-yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # https://github.com/mui-org/material-ui/issues/12432
      - run: yarn --prefer-offline --network-timeout 600000
      - name: Update Versions Static API
        run: yarn release:api
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Trigger Cloudflare Pages to rebuild website
        run: curl -X POST -d '{}' $CLOUDFLARE_PAGES_HOOK_URL
        env:
          CLOUDFLARE_PAGES_HOOK_URL: ${{ secrets.CLOUDFLARE_PAGES_HOOK_URL }}