name: Release APPX

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        app_id: [singlebox, clovery]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: false
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      # https://github.com/mui-org/material-ui/issues/12432
      - run: yarn --prefer-offline --network-timeout 600000
      - name: Release
        run: yarn release:appx
        env:
          APP_ID: ${{ matrix.app_id }}
          CI: true
          DEBUG: electron-packager
          CI_PULL_REQUEST: ${{ github.event_name == 'pull_request' }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # React env
          REACT_APP_AMPLITUDE_API_KEY: ${{ secrets.REACT_APP_AMPLITUDE_API_KEY }}
          REACT_APP_ELASTIC_CLOUD_APP_SEARCH_SEARCH_KEY: ${{ secrets.REACT_APP_ELASTIC_CLOUD_APP_SEARCH_SEARCH_KEY }}
          REACT_APP_ELASTIC_CLOUD_APP_SEARCH_API_ENDPOINT: ${{ secrets.REACT_APP_ELASTIC_CLOUD_APP_SEARCH_API_ENDPOINT }}
          REACT_APP_ELASTIC_CLOUD_APP_SEARCH_ENGINE_NAME: ${{ secrets.REACT_APP_ELASTIC_CLOUD_APP_SEARCH_ENGINE_NAME }}
          # Electron env
          ELECTRON_APP_SENTRY_DSN: ${{ secrets.ELECTRON_APP_SENTRY_DSN }}
          ELECTRON_APP_GOOGLE_API_KEY: ${{ secrets.ELECTRON_APP_GOOGLE_API_KEY }}
          # AWS (for uploading to S3)
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}